### PR TITLE
Remove windows build attempt artifacts

### PR DESCRIPTION
**Pull request by jerinphilip**
(Please squash and merge).

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
I'm pretty sure this will break windows VCPKG static build, as VCPKG adds `static` to the pcre2 static build name.

**Comment by abhi-agg** [comment]
@jerinphilip I just noticed that bergamot-translator's ssplit submodule is using `pcre2-windows-fix` branch instead of `master` of https://github.com/browsermt/ssplit-cpp. Are you planning to merge this PR?

**Comment by abhi-agg** [comment]
@jerinphilip I just noticed that bergamot-translator's ssplit submodule is using `pcre2-windows-fix` branch instead of `master` of https://github.com/browsermt/ssplit-cpp. Are you planning to merge this PR?

**Comment by jerinphilip** [comment]
This is being closed in favour of Nick's approach (https://github.com/ugermann/ssplit-cpp/pull/29). Can @ugermann or someone with write permissions on this repository synchronize so it can be picked up for bergamot-translator?

Thanks,

**Comment by abhi-agg** [comment]
> This is being closed in favour of Nick's approach ([ugermann#29](https://github.com/ugermann/ssplit-cpp/pull/29)). Can @ugermann or someone with write permissions on this repository synchronize so it can be picked up for bergamot-translator?
> 
> Thanks,

I don't have write permissions for master branch. Probably @kpu or @XapaJIaMnu (if @ugermann is unavailable)?

@jerinphilip Btw, are you sure https://github.com/ugermann/ssplit-cpp/pull/29 will resolve the windows build failure in bergamot-translator? https://github.com/browsermt/bergamot-translator/pull/405 still fails on windows.

**Comment by kpu** [comment]
I did a fetch and merge.  Happy @abhi-agg ?

**Comment by abhi-agg** [comment]
@kpu Thanks a lot 👍🏾

**Pull request closed without merging**
